# Generated by Django 2.1.3 on 2018-11-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='usable',
            field=models.BooleanField(default=True, verbose_name='可用性'),
        ),
    ]
