# Generated by Django 2.1.3 on 2018-11-20 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0003_auto_20181119_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='owner',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='chart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='galaxy.Chart', verbose_name='教室座位图'),
        ),
    ]
