# Generated by Django 2.1.3 on 2018-11-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SenderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=256, verbose_name='邮箱')),
                ('subject', models.CharField(default='无主题', max_length=256, verbose_name='主题')),
                ('message', models.TextField(default='', verbose_name='内容')),
                ('submit_time', models.DateTimeField(auto_now=True, verbose_name='提交时间')),
            ],
        ),
    ]
