# Generated by Django 2.1.3 on 2018-11-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0004_auto_20181120_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='current_num',
            field=models.IntegerField(default=0, verbose_name='当前人数'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='slug',
            field=models.CharField(max_length=256, unique=True, verbose_name='班级名称'),
        ),
    ]
